env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    main: ./cmd/gkup-backend
    binary: gkup-backend
    ldflags: -X github.com/Miguel-Dorta/gkup-backend/internal.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: archive
    builds:
      - build
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip